const $=id=>document.getElementById(id);
let currency=localStorage.getItem('pocket-ledger-currency')||'USD',iqdRate=Number(localStorage.getItem('pocket-ledger-iqd-rate'))||1460;
const usdFmt=new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'});
const iqdFmt=new Intl.NumberFormat(undefined,{maximumFractionDigits:0});
const fmt={format:amt=>currency==='IQD'?`${iqdFmt.format(amt*iqdRate)} IQD`:usdFmt.format(amt)};
const categoryLabels={ku:{Food:'خۆراک',Transport:'گواستنەوە',Shopping:'کڕین',Bills:'پسوولەکان',Other:'هیتر',Salary:'موچە',Freelance:'کاری ئازاد',Gift:'دیاری',Rent:'کرێ'}};
const labels={en:{balance:'Current balance',income:'Income',spent:'Spent',allStats:'All monthly statistics',empty:'No transactions yet.'},ku:{balance:'باڵانسی ئێستا',income:'داهات',spent:'خەرجکراو',allStats:'هەموو ئاماری مانگانە',empty:'هیچ مامەڵەیەک نییە.'}};
let entries=JSON.parse(localStorage.getItem('pocket-ledger-entries')||'[]'),lang=localStorage.getItem('pocket-ledger-language')||'en',isDark=localStorage.getItem('pocket-ledger-dark')==='true';
const t=key=>labels[lang][key];
const categoryLabel=x=>lang==='ku'&&categoryLabels.ku[x]?categoryLabels.ku[x]:x;
function valueInMonth(e,y,m){const start=new Date(`${e.date}T12:00:00`),end=new Date(y,m+1,0),r=e.repeat||'once';if(start>end)return 0;if(r==='once')return start.getFullYear()===y&&start.getMonth()===m?e.amount:0;if(r==='yearly')return start.getMonth()===m?e.amount:0;if(r==='monthly')return e.amount;const first=start.getFullYear()===y&&start.getMonth()===m?start.getDate():1;return e.amount*(end.getDate()-first+1)}
function monthKeysWithData(){if(!entries.length)return[];const dates=entries.map(e=>new Date(`${e.date}T12:00:00`));let min=new Date(Math.min(...dates)),max=new Date();if(Math.max(...dates)>max)max=new Date(Math.max(...dates));const keys=[];let cur=new Date(min.getFullYear(),min.getMonth(),1);const last=new Date(max.getFullYear(),max.getMonth(),1);while(cur<=last){keys.push({y:cur.getFullYear(),m:cur.getMonth()});cur.setMonth(cur.getMonth()+1)}return keys.reverse()}
function categoryTotals(y,m){const totals={};entries.forEach(e=>{const v=valueInMonth(e,y,m);if(v>0){const key=`${e.type}:${e.category}`;totals[key]=(totals[key]||0)+v}});return totals}
function render(){const totalIn=entries.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),totalOut=entries.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);$('incomeTotal').textContent=fmt.format(totalIn);$('expenseTotal').textContent=fmt.format(totalOut);$('balance').textContent=fmt.format(totalIn-totalOut);const list=$('monthsList');list.replaceChildren();const keys=monthKeysWithData();if(!keys.length){const p=document.createElement('p');p.textContent=t('empty');p.style.textAlign='center';p.style.color='var(--muted)';list.append(p);return}keys.forEach(({y,m})=>{const node=$('monthCardTemplate').content.firstElementChild.cloneNode(true);const title=new Date(y,m,1).toLocaleDateString(lang==='ku'?'ckb-IQ':undefined,{month:'long',year:'numeric'});node.querySelector('.month-card-title').textContent=title;const income=entries.filter(x=>x.type==='income').reduce((s,x)=>s+valueInMonth(x,y,m),0),expense=entries.filter(x=>x.type==='expense').reduce((s,x)=>s+valueInMonth(x,y,m),0);node.querySelector('.mc-income').textContent=fmt.format(income);node.querySelector('.mc-expense').textContent=fmt.format(expense);node.querySelector('.mc-balance').textContent=fmt.format(income-expense);const totals=categoryTotals(y,m);const breakdown=node.querySelector('.category-breakdown');Object.entries(totals).sort((a,b)=>b[1]-a[1]).forEach(([key,val])=>{const[type,cat]=key.split(':');const row=$('categoryRowTemplate').content.firstElementChild.cloneNode(true);row.querySelector('.category-row-name').textContent=categoryLabel(cat);row.querySelector('.category-row-value').textContent=`${type==='income'?'+':'−'}${fmt.format(val)}`;row.querySelector('.category-row-value').style.color=type==='income'?'#3f8f6b':'var(--expense)';breakdown.append(row)});list.append(node)})}
function localize(){document.documentElement.lang=lang==='ku'?'ckb':'en';document.documentElement.dir=lang==='ku'?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(n=>n.textContent=t(n.dataset.t));$('languageButton').textContent=lang==='en'?'کوردی':'EN';render()}
$('languageButton').onclick=()=>{lang=lang==='en'?'ku':'en';localStorage.setItem('pocket-ledger-language',lang);localize()};
$('themeButton').onclick=()=>{isDark=!isDark;localStorage.setItem('pocket-ledger-dark',isDark);document.body.classList.toggle('dark',isDark);$('themeButton').textContent=isDark?'☀':'☾'};
$('currencyButton').textContent=currency;$('currencyButton').onclick=()=>{currency=currency==='USD'?'IQD':'USD';localStorage.setItem('pocket-ledger-currency',currency);$('currencyButton').textContent=currency;render()};
document.body.classList.toggle('dark',isDark);$('themeButton').textContent=isDark?'☀':'☾';localize();
